services:
  - type: web
    name: pingvista
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: SCHEDULER_INTERVAL_MS
        value: 300000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
